### ISSUE TITLE
what's misc?

### ISSUE THREAD

**Issue by Lanezzz** [guotaowang/STVS#2]
I'm not sure what misc is..Is it another .py file? Can I use it as a reference?https://github.com/zijundeng/DAF/blob/00090cc91dc1fb6ab4bac4298a3deb1815d22d11/misc.py

**Comment by guotaowang** [comment]
Yes, you can use the relevant files for training and testing.

**Comment by Lanezzz** [comment]
> 
> 
> Yes, you can use the relevant files for training and testing.

Thanks for your timely reply   O(∩_∩)O
